# Generated by Django 5.0.4 on 2024-05-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_carrera_id_alter_carrera_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='codigo',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='duracion',
            field=models.IntegerField(verbose_name='Duración (Semestres)'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
    ]
