# Generated by Django 5.0.4 on 2024-05-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_docente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='rut',
            field=models.CharField(max_length=20, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Titulo'),
        ),
    ]
